ONNX版Raspberry Pi向け自動ビルド（armhf）の追加
Hiroshiba/voicevox_core pull request #41
Opened 2021-11-14 21:17 UTC by aoirint

## 内容

ONNX版コアのRaspberry Pi向け自動ビルド（Linux CPU armhf）を追加します。

- [x] ONNX Runtimeのarmhf自動ビルドの作成
- [x] libcoreのarmhf自動ビルドの作成
- [x] ここまでのRaspberry Pi実機動作確認

## 関連 Issue

ref #40

2021-11-16 14:06 UTC, Hiroshiba requested changes
良いですね！！！
いくつか気になったのでコメントしてみました。

ところもしご存知だったら知りたいのですが、公式ビルドはOpenMPをONにしてビルドしているのでしょうか👀
というのもそういえば以前onnxruntimeを使ったときにCPUが100%にならなかったので、もしかしたら使ってないのかなと思った次第です。

2021-11-16 14:06 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          fi
ここでどんな場合でもonnxruntimeを同梱するようにするというのはどうでしょう。
（エンジンビルドのときにonnxruntimeを選ぶ手間が省けるかもと思ったので）

2021-11-16 14:41 UTC, aoirint commented on .github/workflows/build.yml
> +          DOCKERFILE_PATH: ${{ matrix.context_dir }}/Dockerfile
消しミスでした！

2021-11-16 15:50 UTC, aoirint commented on .github/workflows/build.yml
> +          fi
同梱していい気もします。
すべてのONNX Runtimeを入れるとcore.zipの容量が大きくなりそうで、armhf版だけにしていました（Windows GPU版が展開時で300MBくらいあります。ほかは10MB前後ですが）。

2021-11-16 15:50 UTC, aoirint commented on .github/workflows/build.yml
> +          fi
同梱していい気もします。
すべてのONNX Runtimeを入れるとcore.zipの容量が大きくなりそうで、armhf版だけにしていました（Windows GPU版が展開時で300MBくらいあります。ほかは10MB前後ですが）。

2021-11-16 15:57 UTC, aoirint commented
> 公式ビルドはOpenMPをONにしてビルドしているのでしょうか

公式ビルドのOpenMPはv1.7.0から無効化されています（現在はv1.9.1）。外部依存を減らしたい意図があるのかなと思いました。

2021-11-17 14:06 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          fi
確かにcore.zipが大きくなりそうですね･･･
ハードごとに共通のもの（meta.jsonとかcore.hとか）は共通でcore.zipなどにして、
ハードごとに異なるもの（core.dllとかonnxruntimeとか）は別々に小分け.zipにするとか・・・？

とりあえず今はこのままで良いのかなと感じました！

2021-11-17 14:09 UTC, Hiroshiba commented
なるほどです！
PCでの利用だったらCPU使用率が100%になるのは逆に不便なのでOpenMPは無いほうが良さそうだなと感じました。
IoT用途のarmhfは逆に待機する意味がないのでONのほうが良さそうだと思います！

2021-11-17 14:10 UTC, Hiroshiba approved these changes
LGTM！
お試して一回releases作ってみようと思います。

2021-11-17 14:10 UTC, merged